"""Neo4j export utilities for the accountability pipeline.

Generates Cypher scripts and JSON exports for importing data into Neo4j.
Validates referential integrity before export.
"""

from __future__ import annotations

import os
from datetime import date, datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

from accountability_pipeline.models.schemas import RelationshipType
from accountability_pipeline.models.validation import check_referential_integrity
from accountability_pipeline.utils.file_handler import ensure_directory, write_json, write_text
from accountability_pipeline.utils.logger import get_logger

logger = get_logger(__name__)


def _cypher_escape(value: Any) -> str:
    """Escape a value for safe Cypher interpolation."""
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, (date, datetime)):
        return f'date("{value.isoformat()}")'
    if isinstance(value, list):
        items = ", ".join(_cypher_escape(v) for v in value)
        return f"[{items}]"
    s = str(value).replace("\\", "\\\\").replace("'", "\\'").replace('"', '\\"')
    return f'"{s}"'


def _build_properties(record: Dict[str, Any], exclude_keys: Optional[set] = None) -> str:
    """Build a Cypher property map from a dictionary."""
    exclude = exclude_keys or set()
    exclude.update(k for k in record if k.startswith("_"))

    props = []
    for key, value in record.items():
        if key in exclude or value is None:
            continue
        props.append(f"  {key}: {_cypher_escape(value)}")

    return "{\n" + ",\n".join(props) + "\n}" if props else "{}"


def generate_cypher_scripts(
    agents: List[Dict[str, Any]],
    violations: List[Dict[str, Any]],
    incidents: List[Dict[str, Any]],
    output_dir: str,
    employees: Optional[List[Dict[str, Any]]] = None,
    sources: Optional[List[Dict[str, Any]]] = None,
    relationships: Optional[List[Dict[str, Any]]] = None,
) -> Dict[str, str]:
    """Generate ready-to-use Cypher import scripts.

    Creates separate scripts for nodes and relationships, using
    MERGE to avoid duplicates.

    Args:
        agents: List of agent records.
        violations: List of violation records.
        incidents: List of incident records.
        output_dir: Directory to write Cypher files.
        employees: Optional list of employee records.
        sources: Optional list of source records.
        relationships: Optional list of relationship records.

    Returns:
        Dict mapping script name to file path.
    """
    ensure_directory(output_dir)
    scripts: Dict[str, str] = {}

    # Nodes script
    node_lines = [
        "// Auto-generated by Accountability Pipeline",
        f"// Generated at: {datetime.now(timezone.utc).isoformat()}",
        "// Node creation script",
        "",
    ]

    if agents:
        node_lines.append("// --- Agents ---")
        for agent in agents:
            aid = agent.get("id", "")
            props = _build_properties(agent, exclude_keys={"id"})
            node_lines.append(f'MERGE (a:Agent {{id: {_cypher_escape(aid)}}})')
            node_lines.append(f"SET a += {props};")
            node_lines.append("")

    if violations:
        node_lines.append("// --- Violations ---")
        for violation in violations:
            vid = violation.get("id", "")
            props = _build_properties(violation, exclude_keys={"id"})
            node_lines.append(f'MERGE (v:Violation {{id: {_cypher_escape(vid)}}})')
            node_lines.append(f"SET v += {props};")
            node_lines.append("")

    if incidents:
        node_lines.append("// --- Incidents ---")
        for incident in incidents:
            iid = incident.get("id", "")
            props = _build_properties(incident, exclude_keys={"id"})
            node_lines.append(f'MERGE (i:Incident {{id: {_cypher_escape(iid)}}})')
            node_lines.append(f"SET i += {props};")
            node_lines.append("")

    if employees:
        node_lines.append("// --- Employees ---")
        for emp in employees:
            eid = emp.get("id", "")
            props = _build_properties(emp, exclude_keys={"id"})
            node_lines.append(f'MERGE (e:Employee {{id: {_cypher_escape(eid)}}})')
            node_lines.append(f"SET e += {props};")
            node_lines.append("")

    if sources:
        node_lines.append("// --- Sources ---")
        for source in sources:
            sid = source.get("id", "")
            props = _build_properties(source, exclude_keys={"id"})
            node_lines.append(f'MERGE (s:Source {{id: {_cypher_escape(sid)}}})')
            node_lines.append(f"SET s += {props};")
            node_lines.append("")

    nodes_path = os.path.join(output_dir, "01-import-nodes.cypher")
    write_text("\n".join(node_lines), nodes_path)
    scripts["nodes"] = nodes_path

    # Relationships script
    if relationships:
        rel_lines = [
            "// Auto-generated by Accountability Pipeline",
            f"// Generated at: {datetime.now(timezone.utc).isoformat()}",
            "// Relationship creation script",
            "",
        ]

        label_map = _build_label_map(agents, violations, incidents, employees or [], sources or [])

        for rel in relationships:
            source_id = rel.get("source_id", "")
            target_id = rel.get("target_id", "")
            rel_type = rel.get("relationship_type", "RELATED_TO")
            props = rel.get("properties", {})

            source_label = label_map.get(source_id, "Agent")
            target_label = label_map.get(target_id, "Violation")

            rel_lines.append(
                f"MATCH (a:{source_label} {{id: {_cypher_escape(source_id)}}})"
            )
            rel_lines.append(
                f"MATCH (b:{target_label} {{id: {_cypher_escape(target_id)}}})"
            )

            if props:
                props_str = _build_properties(props)
                rel_lines.append(f"MERGE (a)-[r:{rel_type}]->(b)")
                rel_lines.append(f"SET r += {props_str};")
            else:
                rel_lines.append(f"MERGE (a)-[:{rel_type}]->(b);")
            rel_lines.append("")

        rels_path = os.path.join(output_dir, "02-import-relationships.cypher")
        write_text("\n".join(rel_lines), rels_path)
        scripts["relationships"] = rels_path

    logger.info("cypher_generated", scripts=list(scripts.keys()), output_dir=output_dir)
    return scripts


def _build_label_map(
    agents: List[Dict],
    violations: List[Dict],
    incidents: List[Dict],
    employees: List[Dict],
    sources: List[Dict],
) -> Dict[str, str]:
    """Build a mapping from entity ID to Neo4j label."""
    label_map = {}
    for a in agents:
        if "id" in a:
            label_map[a["id"]] = "Agent"
    for v in violations:
        if "id" in v:
            label_map[v["id"]] = "Violation"
    for i in incidents:
        if "id" in i:
            label_map[i["id"]] = "Incident"
    for e in employees:
        if "id" in e:
            label_map[e["id"]] = "Employee"
    for s in sources:
        if "id" in s:
            label_map[s["id"]] = "Source"
    return label_map


def generate_json_export(
    data: Dict[str, List[Dict[str, Any]]],
    output_dir: str,
) -> Dict[str, str]:
    """Generate Neo4j-import-format JSON files.

    Creates separate JSON files for each entity type, compatible with
    neo4j-admin import and APOC procedures.

    Args:
        data: Dictionary mapping entity type to list of records.
            Keys: 'agents', 'violations', 'incidents', 'employees', 'sources', 'relationships'.
        output_dir: Directory to write JSON files.

    Returns:
        Dict mapping entity type to file path.
    """
    ensure_directory(output_dir)
    exports: Dict[str, str] = {}

    for entity_type, records in data.items():
        if not records:
            continue

        clean_records = []
        for record in records:
            clean = {k: _serialize_value(v) for k, v in record.items() if not k.startswith("_")}
            clean_records.append(clean)

        file_path = os.path.join(output_dir, f"{entity_type}.json")
        write_json(clean_records, file_path)
        exports[entity_type] = file_path

    logger.info("json_exported", entity_types=list(exports.keys()), output_dir=output_dir)
    return exports


def _serialize_value(value: Any) -> Any:
    """Serialize a value for JSON export."""
    if isinstance(value, (date, datetime)):
        return value.isoformat()
    if isinstance(value, set):
        return list(value)
    return value


def validate_neo4j_readiness(
    data: Dict[str, List[Dict[str, Any]]],
) -> Tuple[bool, List[str]]:
    """Check that data is ready for Neo4j import.

    Validates:
    - All records have required 'id' fields
    - All relationship endpoints exist
    - No duplicate IDs within entity types

    Args:
        data: Dictionary mapping entity type to records.

    Returns:
        Tuple of (is_ready, list_of_issues).
    """
    issues: List[str] = []

    # Check for missing IDs
    node_types = ["agents", "violations", "incidents", "employees", "sources"]
    for ntype in node_types:
        records = data.get(ntype, [])
        for i, record in enumerate(records):
            if not record.get("id"):
                issues.append(f"{ntype}[{i}]: missing 'id' field")

    # Check for duplicate IDs
    for ntype in node_types:
        records = data.get(ntype, [])
        ids = [r.get("id") for r in records if r.get("id")]
        seen = set()
        for rid in ids:
            if rid in seen:
                issues.append(f"{ntype}: duplicate id '{rid}'")
            seen.add(rid)

    # Check referential integrity
    agents = data.get("agents", [])
    violations = data.get("violations", [])
    incidents = data.get("incidents", [])
    relationships = data.get("relationships", [])

    _, ref_issues = check_referential_integrity(agents, violations, incidents, relationships)
    issues.extend(ref_issues)

    is_ready = len(issues) == 0
    if is_ready:
        logger.info("neo4j_validation_passed")
    else:
        logger.warning("neo4j_validation_failed", issue_count=len(issues))

    return is_ready, issues
